name: "Test and Deploy"

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install
              run: npm ci
            - name: lint
              run: npm run lint
            - name: build
              run: npm run build
            - name: format
              run: npm run format:check
              env:
                  CI: true
    deploy:
        runs-on: ubuntu-latest
        needs: test
        if: github.ref == 'refs/heads/kube-test'
        steps:
            - uses: actions/checkout@v2

            - uses: Azure/docker-login@v1
              with:
                  login-server: https://index.docker.io/v1/
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - run: |
                  docker build . -t lumieducation/homepage:${{ github.sha }}
                  docker push lumieducation/homepage:${{ github.sha }}

            - uses: azure/k8s-set-context@v1
              with:
                method: service-account
                k8s-url: ${{ secrets.K8S_URL }}
                k8s-secret: ${{ secrets.K8S_SECRET }}
              id: setcontext

            - uses: azure/setup-kubectl@v1
              id: install

            - uses: azure/k8s-deploy@v1.4
              with:
                  namespace: ${{ secrets.K8S_NAMESPACE }}
                  manifests: |
                      manifests/deployment.yaml
                      manifests/service.yaml
                      manifests/ingress.yaml
                  images: |
                      lumieducation/homepage:${{ github.sha }}
                  token: ${{ secrets.GITHUB_TOKEN }}